/**
 * cocktails.js - 鸡尾酒数据库
 *
 * 数据结构：
 * {
 *   id: string,              // 唯一标识
 *   name: string,            // 中文名
 *   nameEn: string,          // 英文名
 *   category: string,        // 分类：classic / tropical / modern / spirit-forward / creamy
 *   image: string,           // 图片路径
 *   glass: string,           // 杯型
 *   structure: string,       // 结构类型：highball/sour/martini/old-fashioned/fizz/collins/manhattan/margarita/tiki/flip
 *   baseSpirit: string,      // 基酒：gin/vodka/rum/whiskey/tequila
 *   strength: number,        // 烈度 1-5
 *   sweetness: number,       // 甜度 1-5
 *   abv: number,             // 酒精度 (%)
 *   color: string,           // 颜色名称
 *   difficulty: number,      // 制作难度 1-3
 *   rating: number,          // 评分 1-5
 *   mbtiMatch: string[],     // 匹配的 MBTI 类型
 *   description: string,     // 一句话描述
 *   story: string,           // 背景故事
 *   method: string,          // 调制技法：shake / stir / build / blend / dry-shake / muddle & build
 *   methodLabel: string,     // 技法中文名：摇和法 / 搅拌法 / 直调法 / 搅拌机法 / 干摇法 / 捣拌直调法
 *   ingredients: Array<{name, amount, unit, category}>,
 *   garnish: string,         // 装饰
 *   flavorNotes: string[],   // 风味标签
 *   scene: string[],         // 适合场景
 *   tags: string[]           // 标签
 * }
 */

export default [
  // ==================== 金酒 Gin ====================
  {
    id: 'negroni',
    name: '尼格罗尼',
    nameEn: 'Negroni',
    category: 'classic',
    image: '',
    glass: '古典杯',
    structure: 'old-fashioned',
    baseSpirit: 'gin',
    strength: 4,
    sweetness: 2,
    abv: 24,
    color: '深宝石红',
    difficulty: 1,
    rating: 4.8,
    mbtiMatch: ['INTJ', 'ENTJ', 'INFJ'],
    description: '苦甜交织的经典，深邃而复杂，如同战略家的内心世界。',
    story: '1919 年诞生于意大利佛罗伦萨，由 Camillo Negroni 伯爵首创。他将金酒的清爽、甜味美思的圆润与金巴利的苦味完美融合，创造出这款风靡全球的经典。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '金酒', amount: '30', unit: 'ml', category: 'base' },
      { name: '甜味美思', amount: '30', unit: 'ml', category: 'modifier' },
      { name: '金巴利', amount: '30', unit: 'ml', category: 'modifier' }
    ],
    garnish: '橙皮',
    flavorNotes: ['苦味', '草本', '柑橘', '甜味美思'],
    scene: ['独饮', '商务', '餐前'],
    tags: ['经典', '苦味', '意大利', '餐前酒', 'IBA']
  },
  {
    id: 'gin-tonic',
    name: '金汤力',
    nameEn: 'Gin & Tonic',
    category: 'classic',
    image: '',
    glass: '高球杯',
    structure: 'highball',
    baseSpirit: 'gin',
    strength: 2,
    sweetness: 1,
    abv: 12,
    color: '透明',
    difficulty: 1,
    rating: 4.3,
    mbtiMatch: ['INFP', 'ISFP', 'ENFP'],
    description: '清爽通透的永恒组合，随性自在，如同艺术家的灵感流动。',
    story: '最初是英国东印度公司士兵为对抗疟疾而发明的——将奎宁水与金酒混合以掩盖苦味。如今已成为全球最受欢迎的鸡尾酒之一。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '金酒', amount: '45', unit: 'ml', category: 'base' },
      { name: '汤力水', amount: '120', unit: 'ml', category: 'mixer' },
      { name: '青柠角', amount: '2', unit: '个', category: 'garnish' }
    ],
    garnish: '青柠角、杜松子',
    flavorNotes: ['清爽', '气泡', '杜松子', '柑橘'],
    scene: ['派对', '夏日', '独饮'],
    tags: ['经典', '清爽', '英国', '长饮']
  },
  {
    id: 'dry-martini',
    name: '干马天尼',
    nameEn: 'Dry Martini',
    category: 'classic',
    image: '',
    glass: '马天尼杯',
    structure: 'martini',
    baseSpirit: 'gin',
    strength: 5,
    sweetness: 1,
    abv: 32,
    color: '透明',
    difficulty: 2,
    rating: 4.9,
    mbtiMatch: ['INTJ', 'ISTJ', 'ENTJ'],
    description: '极致的简洁与纯粹，是理性主义者的液体宣言。',
    story: '关于马天尼的起源众说纷纭，最广泛的说法是 1860 年代由旧金山的调酒师 Jerry Thomas 首创。丘吉尔、海明威和罗斯福都是其忠实爱好者。007 那句"Shaken, not stirred"更让它成为文化符号。',
    method: 'stir',
    methodLabel: '搅拌法',
    ingredients: [
      { name: '伦敦干金酒', amount: '60', unit: 'ml', category: 'base' },
      { name: '干味美思', amount: '10', unit: 'ml', category: 'modifier' }
    ],
    garnish: '橄榄或柠檬皮',
    flavorNotes: ['干型', '杜松子', '草本', '极简'],
    scene: ['独饮', '商务', '正式场合'],
    tags: ['经典', '极简', '优雅', 'IBA', '标志性']
  },
  {
    id: 'gin-fizz',
    name: '金菲士',
    nameEn: 'Gin Fizz',
    category: 'classic',
    image: '',
    glass: '菲士杯',
    structure: 'fizz',
    baseSpirit: 'gin',
    strength: 2,
    sweetness: 3,
    abv: 14,
    color: '乳白',
    difficulty: 2,
    rating: 4.2,
    mbtiMatch: ['ISFJ', 'ESFJ', 'INFP'],
    description: '绵密气泡中的温柔，如春风拂面般的细腻体验。',
    story: '诞生于 19 世纪末的美国新奥尔良，是菲士家族的开山之作。它完美地平衡了酸、甜、气泡和丝滑口感，是早午餐和午后时光的经典选择。',
    method: 'shake',
    methodLabel: '摇和法',
    ingredients: [
      { name: '金酒', amount: '45', unit: 'ml', category: 'base' },
      { name: '新鲜柠檬汁', amount: '22', unit: 'ml', category: 'acid' },
      { name: '单糖浆', amount: '15', unit: 'ml', category: 'sweetener' },
      { name: '苏打水', amount: '60', unit: 'ml', category: 'mixer' }
    ],
    garnish: '柠檬片',
    flavorNotes: ['气泡', '柑橘', '清爽', '微甜'],
    scene: ['夏日', '早午餐', '派对'],
    tags: ['经典', '气泡', '清爽', '长饮']
  },
  {
    id: 'tom-collins',
    name: '汤姆柯林斯',
    nameEn: 'Tom Collins',
    category: 'classic',
    image: '',
    glass: '柯林斯杯',
    structure: 'collins',
    baseSpirit: 'gin',
    strength: 2,
    sweetness: 3,
    abv: 13,
    color: '透明微白',
    difficulty: 1,
    rating: 4.1,
    mbtiMatch: ['ESFP', 'ESTP', 'ENFJ'],
    description: '长饮之王的经典魅力，社交场合的永恒选择。',
    story: '1876 年由纽约调酒师 Jerry Thomas 创作，是最早的柯林斯类鸡尾酒。传说灵感来自一个恶作剧——告诉路人有个叫 Tom Collins 的人在散布谣言，引发了一场全城"寻找 Tom Collins"的热潮。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '金酒', amount: '45', unit: 'ml', category: 'base' },
      { name: '新鲜柠檬汁', amount: '22', unit: 'ml', category: 'acid' },
      { name: '单糖浆', amount: '15', unit: 'ml', category: 'sweetener' },
      { name: '苏打水', amount: '90', unit: 'ml', category: 'mixer' }
    ],
    garnish: '柠檬轮、樱桃',
    flavorNotes: ['柑橘', '气泡', '清爽', '微甜'],
    scene: ['派对', '夏日', '社交'],
    tags: ['经典', '长饮', '清爽', '社交']
  },
  {
    id: 'clover-club',
    name: '三叶草俱乐部',
    nameEn: 'Clover Club',
    category: 'classic',
    image: '',
    glass: '马天尼杯',
    structure: 'sour',
    baseSpirit: 'gin',
    strength: 2,
    sweetness: 3,
    abv: 16,
    color: '粉红',
    difficulty: 2,
    rating: 4.3,
    mbtiMatch: ['ENFJ', 'ESFJ', 'ISFP'],
    description: '粉色优雅的绅士之选，蛋清赋予的丝绒口感令人难忘。',
    story: '诞生于 20 世纪初费城的 Clover Club 绅士俱乐部，曾是律师、银行家等社会名流的挚爱。一度失传后在鸡尾酒复兴运动中重回大众视野，成为经典复兴的标杆。',
    method: 'shake',
    methodLabel: '摇和法',
    ingredients: [
      { name: '金酒', amount: '45', unit: 'ml', category: 'base' },
      { name: '新鲜柠檬汁', amount: '15', unit: 'ml', category: 'acid' },
      { name: '覆盆子糖浆', amount: '15', unit: 'ml', category: 'sweetener' },
      { name: '蛋清', amount: '15', unit: 'ml', category: 'modifier' }
    ],
    garnish: '覆盆子',
    flavorNotes: ['莓果', '丝滑', '花香', '微酸'],
    scene: ['约会', '社交', '午后'],
    tags: ['经典', '优雅', '蛋清', '粉红']
  },

  {
    id: 'aviation',
    name: '航空',
    nameEn: 'Aviation',
    category: 'classic',
    image: '',
    glass: '马天尼杯',
    structure: 'sour',
    baseSpirit: 'gin',
    strength: 3,
    sweetness: 2,
    abv: 24,
    color: '淡紫',
    difficulty: 2,
    rating: 4.5,
    mbtiMatch: ['INFP', 'ISFP', 'INFJ'],
    description: '紫罗兰与樱桃利口酒交织的花香经典，如云上飞行的轻盈梦境。',
    story: '1916 年诞生于纽约 Hotel Wallick，由 Hugo Ensslin 记录于《Recipes for Mixed Drinks》。紫罗兰利口酒一度停产让这杯酒几近失传，直到 2000 年代精酿鸡尾酒复兴才重回酒单，成为花香系酸酒的代表。',
    method: 'shake',
    methodLabel: '摇和法',
    ingredients: [
      { name: '金酒', amount: '45', unit: 'ml', category: 'base' },
      { name: '黑樱桃利口酒', amount: '15', unit: 'ml', category: 'modifier' },
      { name: '紫罗兰利口酒', amount: '10', unit: 'ml', category: 'modifier' },
      { name: '新鲜柠檬汁', amount: '20', unit: 'ml', category: 'acid' }
    ],
    garnish: '樱桃',
    flavorNotes: ['花香', '果味', '柑橘', '樱桃'],
    scene: ['独饮', '餐前', '社交'],
    tags: ['经典', '花香', 'IBA', '禁酒令时代']
  },
  {
    id: 'gimlet',
    name: '吉姆雷特',
    nameEn: 'Gimlet',
    category: 'classic',
    image: '',
    glass: '马天尼杯',
    structure: 'sour',
    baseSpirit: 'gin',
    strength: 3,
    sweetness: 2,
    abv: 26,
    color: '淡绿',
    difficulty: 1,
    rating: 4.2,
    mbtiMatch: ['INTJ', 'ISTJ', 'ISTP'],
    description: '金酒与青柠的极简二重奏，干爽利落，毫无多余修饰。',
    story: '源于英国海军防坏血病的传统——Lauchlin Rose 爵士发明青柠浓缩汁后与船员配给的杜松子酒结合。雷蒙德·钱德勒在《漫长的告别》中写道："真正的吉姆雷特，是金酒与玫瑰的相遇。"',
    method: 'shake',
    methodLabel: '摇和法',
    ingredients: [
      { name: '金酒', amount: '60', unit: 'ml', category: 'base' },
      { name: '新鲜青柠汁', amount: '22', unit: 'ml', category: 'acid' },
      { name: '单糖浆', amount: '15', unit: 'ml', category: 'sweetener' }
    ],
    garnish: '青柠轮',
    flavorNotes: ['青柠', '柑橘', '干型', '清爽'],
    scene: ['独饮', '餐前'],
    tags: ['经典', '极简', 'IBA', '酸酒']
  },
  {
    id: 'white-lady',
    name: '白色佳人',
    nameEn: 'White Lady',
    category: 'classic',
    image: '',
    glass: '马天尼杯',
    structure: 'sour',
    baseSpirit: 'gin',
    strength: 3,
    sweetness: 2,
    abv: 26,
    color: '透明',
    difficulty: 2,
    rating: 4.3,
    mbtiMatch: ['ENTP', 'ESTP', 'INTP'],
    description: '金酒、橙酒与柠檬的锋利平衡，优雅外表下的凌厉口感。',
    story: '诞生于 1920 年代伦敦萨伏依酒店，传说由 Harry MacElhone（后巴黎 Harry\'s New York Bar 创始人）首创。金酒替换掉早期版本的君度做基酒后，三原料的经典配比就此定稿，与 Sidecar、Marguerite 并称酸酒三杰。',
    method: 'shake',
    methodLabel: '摇和法',
    ingredients: [
      { name: '金酒', amount: '40', unit: 'ml', category: 'base' },
      { name: '君度橙酒', amount: '20', unit: 'ml', category: 'modifier' },
      { name: '新鲜柠檬汁', amount: '20', unit: 'ml', category: 'acid' }
    ],
    garnish: '柠檬皮',
    flavorNotes: ['柑橘', '橙子', '干型', '清爽'],
    scene: ['社交', '餐前'],
    tags: ['经典', 'IBA', '禁酒令时代']
  },
  {
    id: 'singapore-sling',
    name: '新加坡司令',
    nameEn: 'Singapore Sling',
    category: 'tropical',
    image: '',
    glass: '飓风杯',
    structure: 'collins',
    baseSpirit: 'gin',
    strength: 2,
    sweetness: 4,
    abv: 12,
    color: '粉红',
    difficulty: 3,
    rating: 4.1,
    mbtiMatch: ['ESFP', 'ENFP', 'ESFJ'],
    description: '层次繁复的热带长饮，粉红外观下藏着七种原料的精妙协作。',
    story: '1915 年诞生于新加坡莱佛士酒店 Long Bar，调酒师严崇文为让女士也能体面地饮酒而创——粉红色泽让它伪装成"果汁"。这杯亚洲对鸡尾酒世界最著名的贡献，至今仍是来佛士酒店的活招牌。',
    method: 'shake',
    methodLabel: '摇和法',
    ingredients: [
      { name: '金酒', amount: '30', unit: 'ml', category: 'base' },
      { name: '黑樱桃利口酒', amount: '15', unit: 'ml', category: 'modifier' },
      { name: '君度橙酒', amount: '10', unit: 'ml', category: 'modifier' },
      { name: '菠萝汁', amount: '90', unit: 'ml', category: 'acid' },
      { name: '新鲜青柠汁', amount: '15', unit: 'ml', category: 'acid' },
      { name: '红石榴糖浆', amount: '10', unit: 'ml', category: 'sweetener' },
      { name: '安格斯特拉苦精', amount: '1', unit: '滴', category: 'modifier' }
    ],
    garnish: '菠萝角',
    flavorNotes: ['热带水果', '菠萝', '果味', '甜美'],
    scene: ['社交', '夏日', '派对'],
    tags: ['经典', '热带', 'IBA', '长饮']
  },
  {
    id: 'french-75',
    name: '法式75',
    nameEn: 'French 75',
    category: 'classic',
    image: '',
    glass: '香槟杯',
    structure: 'fizz',
    baseSpirit: 'gin',
    strength: 3,
    sweetness: 2,
    abv: 20,
    color: '金色',
    difficulty: 2,
    rating: 4.4,
    mbtiMatch: ['ENFJ', 'ENTJ', 'ESFJ'],
    description: '金酒与香槟的庆典组合，优雅气泡中藏着"75毫米野战炮"的后劲。',
    story: '一战期间诞生于巴黎 Harry\'s New York Bar，以法国 75mm 野战炮命名——"喝下它如同被炮火击中"。1930 年列入《萨伏依鸡尾酒书》，从此成为庆祝场合的永恒之选。',
    method: 'shake',
    methodLabel: '摇和法',
    ingredients: [
      { name: '金酒', amount: '30', unit: 'ml', category: 'base' },
      { name: '新鲜柠檬汁', amount: '15', unit: 'ml', category: 'acid' },
      { name: '单糖浆', amount: '10', unit: 'ml', category: 'sweetener' },
      { name: '香槟', amount: '60', unit: 'ml', category: 'mixer' }
    ],
    garnish: '柠檬皮',
    flavorNotes: ['气泡', '柑橘', '清爽', '干型'],
    scene: ['社交', '派对', '餐前'],
    tags: ['经典', '气泡', 'IBA', '香槟']
  },
  {
    id: 'vesper',
    name: '维斯珀',
    nameEn: 'Vesper',
    category: 'modern',
    image: '',
    glass: '马天尼杯',
    structure: 'martini',
    baseSpirit: 'gin',
    strength: 5,
    sweetness: 1,
    abv: 35,
    color: '透明',
    difficulty: 2,
    rating: 4.5,
    mbtiMatch: ['INTJ', 'ISTP', 'ENTJ'],
    description: '邦德专属的烈性马天尼变体，冰冷、锐利、致命优雅。',
    story: '1953 年伊恩·弗莱明在《皇家赌场》中为特工 007 设计："摇匀，不要搅拌。"以女主角 Vesper Lynd 命名——一杯酒与一段刻骨铭心的爱情一同成为传奇，配方原稿要求"加一片大而薄的柠檬皮"。',
    method: 'stir',
    methodLabel: '搅拌法',
    ingredients: [
      { name: '金酒', amount: '60', unit: 'ml', category: 'base' },
      { name: '伏特加', amount: '15', unit: 'ml', category: 'base' },
      { name: '干味美思', amount: '10', unit: 'ml', category: 'modifier' }
    ],
    garnish: '柠檬皮',
    flavorNotes: ['干型', '草本', '杜松子', '复杂'],
    scene: ['独饮', '商务'],
    tags: ['现代', '烈酒', 'IBA', '007']
  },
  {
    id: 'bramble',
    name: '荆棘',
    nameEn: 'Bramble',
    category: 'modern',
    image: '',
    glass: '古典杯',
    structure: 'sour',
    baseSpirit: 'gin',
    strength: 3,
    sweetness: 3,
    abv: 22,
    color: '粉红',
    difficulty: 2,
    rating: 4.2,
    mbtiMatch: ['INFP', 'ISFP', 'ENFP'],
    description: '碎冰上晕染开的黑莓纹路如荒野荆棘，酸甜交织的英伦夏日。',
    story: '1984 年由伦敦调酒师 Dick Bradsell 在 Fred\'s Club 首创，灵感来自他童年时在怀特岛采黑莓的记忆。"酸酒基底 + 利口酒淋面"的手法开创了 80 年代英伦新经典流派。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '金酒', amount: '50', unit: 'ml', category: 'base' },
      { name: '新鲜柠檬汁', amount: '25', unit: 'ml', category: 'acid' },
      { name: '单糖浆', amount: '10', unit: 'ml', category: 'sweetener' },
      { name: '黑莓利口酒', amount: '15', unit: 'ml', category: 'modifier' }
    ],
    garnish: '柠檬片',
    flavorNotes: ['莓果', '果味', '柑橘', '甜美'],
    scene: ['夏日', '社交'],
    tags: ['现代', '英伦', 'IBA', '莓果']
  },
  // ==================== 威士忌 Whiskey ====================
  {
    id: 'old-fashioned',
    name: '古典鸡尾酒',
    nameEn: 'Old Fashioned',
    category: 'spirit-forward',
    image: '',
    glass: '古典杯',
    structure: 'old-fashioned',
    baseSpirit: 'whiskey',
    strength: 5,
    sweetness: 2,
    abv: 33,
    color: '琥珀',
    difficulty: 1,
    rating: 4.9,
    mbtiMatch: ['INFJ', 'ISFJ', 'ISTJ'],
    description: '极简中的极致，回归本源，如同守护者般温柔而坚定。',
    story: '最早可追溯到 1806 年，被誉为"鸡尾酒鼻祖"。它以最少的材料展现威士忌的原始魅力，是懂得品味的人的终极选择。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '波本或黑麦威士忌', amount: '60', unit: 'ml', category: 'base' },
      { name: '方糖', amount: '1', unit: '块', category: 'sweetener' },
      { name: '安格斯特拉苦精', amount: '3', unit: '滴', category: 'modifier' },
      { name: '苏打水', amount: '少许', unit: '', category: 'mixer' }
    ],
    garnish: '橙皮、樱桃',
    flavorNotes: ['橡木', '焦糖', '苦精', '柑橘皮'],
    scene: ['独饮', '商务', '冬日'],
    tags: ['经典', '烈酒', '美国', '老派', 'IBA']
  },
  {
    id: 'whiskey-sour',
    name: '威士忌酸',
    nameEn: 'Whiskey Sour',
    category: 'classic',
    image: '',
    glass: '古典杯',
    structure: 'sour',
    baseSpirit: 'whiskey',
    strength: 3,
    sweetness: 3,
    abv: 20,
    color: '金黄',
    difficulty: 2,
    rating: 4.5,
    mbtiMatch: ['ISTJ', 'ESTJ', 'ENTJ'],
    description: '酸甜平衡的经典之作，沉稳可靠，如同守护者的品格。',
    story: '最早的威士忌酸配方可追溯到 1862 年 Jerry Thomas 的调酒指南。它简单却完美，是考验调酒师基本功的试金石。',
    method: 'shake',
    methodLabel: '摇和法',
    ingredients: [
      { name: '波本威士忌', amount: '60', unit: 'ml', category: 'base' },
      { name: '新鲜柠檬汁', amount: '22', unit: 'ml', category: 'acid' },
      { name: '单糖浆', amount: '15', unit: 'ml', category: 'sweetener' },
      { name: '蛋清（可选）', amount: '15', unit: 'ml', category: 'modifier' }
    ],
    garnish: '柠檬片、樱桃',
    flavorNotes: ['柑橘', '焦糖', '丝滑', '酸甜'],
    scene: ['独饮', '社交', '餐后'],
    tags: ['经典', '酸甜', '美国', '入门']
  },
  {
    id: 'manhattan',
    name: '曼哈顿',
    nameEn: 'Manhattan',
    category: 'spirit-forward',
    image: '',
    glass: '马天尼杯',
    structure: 'manhattan',
    baseSpirit: 'whiskey',
    strength: 5,
    sweetness: 2,
    abv: 30,
    color: '深琥珀',
    difficulty: 1,
    rating: 4.8,
    mbtiMatch: ['INTJ', 'ENTJ', 'ISTJ'],
    description: '纽约的液体名片，威士忌与味美思的世纪联姻。',
    story: '据说 1874 年诞生于纽约曼哈顿俱乐部，由丘吉尔的母亲 Jennie Jerome 举办的宴会上首次调制。此后成为全球五大经典鸡尾酒之一，是威士忌爱好者的必修课。',
    method: 'stir',
    methodLabel: '搅拌法',
    ingredients: [
      { name: '黑麦威士忌', amount: '60', unit: 'ml', category: 'base' },
      { name: '甜味美思', amount: '30', unit: 'ml', category: 'modifier' },
      { name: '安格斯特拉苦精', amount: '2', unit: '滴', category: 'modifier' }
    ],
    garnish: '樱桃',
    flavorNotes: ['橡木', '香草', '草药', '辛辣'],
    scene: ['商务', '正式场合', '独饮'],
    tags: ['经典', '烈酒', '纽约', '优雅', 'IBA']
  },
  {
    id: 'mint-julep',
    name: '薄荷朱莉普',
    nameEn: 'Mint Julep',
    category: 'classic',
    image: '',
    glass: '朱莉普杯',
    structure: 'old-fashioned',
    baseSpirit: 'whiskey',
    strength: 3,
    sweetness: 3,
    abv: 25,
    color: '淡琥珀',
    difficulty: 2,
    rating: 4.3,
    mbtiMatch: ['ISTP', 'ESTP', 'ISFP'],
    description: '碎冰中的薄荷清凉，肯塔基赛马会的标志性饮品。',
    story: '源自 18 世纪美国南部，最初是药用的晨间饮品。"Julep"一词来自波斯语"golab"（玫瑰水）。如今是肯塔基赛马会的官方饮品，每年消耗超过 12 万杯。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '波本威士忌', amount: '60', unit: 'ml', category: 'base' },
      { name: '新鲜薄荷叶', amount: '10', unit: '片', category: 'modifier' },
      { name: '白砂糖', amount: '10', unit: 'g', category: 'sweetener' },
      { name: '碎冰', amount: '满杯', unit: '', category: 'mixer' }
    ],
    garnish: '薄荷枝',
    flavorNotes: ['薄荷', '焦糖', '冰凉', '草本'],
    scene: ['夏日', '户外', '独饮'],
    tags: ['经典', '清凉', '美国南部', '赛马']
  },
  {
    id: 'boulevardier',
    name: '林荫大道',
    nameEn: 'Boulevardier',
    category: 'spirit-forward',
    image: '',
    glass: '古典杯',
    structure: 'old-fashioned',
    baseSpirit: 'whiskey',
    strength: 4,
    sweetness: 2,
    abv: 25,
    color: '深宝石红',
    difficulty: 1,
    rating: 4.5,
    mbtiMatch: ['INTJ', 'INFJ', 'ENTP'],
    description: '威士忌版的尼格罗尼，更深沉更温暖，如同巴黎深秋的午后。',
    story: '1927 年由旅居巴黎的美国作家 Erskine Gwynne 创作，以他创办的文学杂志《Boulevardier》命名。它是尼格罗尼的威士忌变体——用波本替代金酒，带来更温暖的味觉体验。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '波本威士忌', amount: '45', unit: 'ml', category: 'base' },
      { name: '甜味美思', amount: '22', unit: 'ml', category: 'modifier' },
      { name: '金巴利', amount: '22', unit: 'ml', category: 'modifier' }
    ],
    garnish: '橙皮',
    flavorNotes: ['苦味', '焦糖', '草本', '橡木'],
    scene: ['冬日', '独饮', '餐前'],
    tags: ['经典', '苦甜', '巴黎', '冬季']
  },
  {
    id: 'sazerac',
    name: '萨泽拉克',
    nameEn: 'Sazerac',
    category: 'spirit-forward',
    image: '',
    glass: '古典杯',
    structure: 'old-fashioned',
    baseSpirit: 'whiskey',
    strength: 5,
    sweetness: 2,
    abv: 35,
    color: '琥珀',
    difficulty: 2,
    rating: 4.7,
    mbtiMatch: ['ISTP', 'INTJ', 'ISTJ'],
    description: '新奥尔良的灵魂之酒，苦艾的茴香气息与黑麦的辛辣交织。',
    story: '被公认为美国最古老的鸡尾酒之一，1838 年诞生于新奥尔良。最初使用法国 Sazerac 白兰地，后来因根瘤蚜虫害改用黑麦威士忌。2008 年被路易斯安那州立法定为官方州酒。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '黑麦威士忌', amount: '60', unit: 'ml', category: 'base' },
      { name: '方糖', amount: '1', unit: '块', category: 'sweetener' },
      { name: '佩肖苦精', amount: '4', unit: '滴', category: 'modifier' },
      { name: '苦艾酒', amount: '5', unit: 'ml', category: 'modifier' }
    ],
    garnish: '柠檬皮',
    flavorNotes: ['辛辣', '茴香', '焦糖', '苦精'],
    scene: ['独饮', '冬日', '商务'],
    tags: ['经典', '美国最古老', '新奥尔良', 'IBA']
  },

  {
    id: 'rob-roy',
    name: '罗伯罗伊',
    nameEn: 'Rob Roy',
    category: 'classic',
    image: '',
    glass: '马天尼杯',
    structure: 'manhattan',
    baseSpirit: 'whiskey',
    strength: 4,
    sweetness: 2,
    abv: 30,
    color: '琥珀',
    difficulty: 1,
    rating: 4.3,
    mbtiMatch: ['ESTJ', 'ENTJ', 'ISTJ'],
    description: '曼哈顿的苏格兰版本，烟熏麦芽与甜味美思的沉稳对话。',
    story: '1894 年诞生于纽约华尔道夫酒店，为推广歌剧《罗伯罗伊》而创。以苏格兰民间英雄 Rob Roy MacGregor 命名，把曼哈顿公式移植到苏格兰麦芽威士忌上，成为最经典的曼哈顿变体。',
    method: 'stir',
    methodLabel: '搅拌法',
    ingredients: [
      { name: '苏格兰威士忌', amount: '60', unit: 'ml', category: 'base' },
      { name: '甜味美思', amount: '30', unit: 'ml', category: 'modifier' },
      { name: '安格斯特拉苦精', amount: '2', unit: '滴', category: 'modifier' }
    ],
    garnish: '樱桃',
    flavorNotes: ['烟熏', '草本', '干型', '复杂'],
    scene: ['商务', '餐后', '独饮'],
    tags: ['经典', 'IBA', '威士忌']
  },
  {
    id: 'penicillin',
    name: '盘尼西林',
    nameEn: 'Penicillin',
    category: 'modern',
    image: '',
    glass: '古典杯',
    structure: 'sour',
    baseSpirit: 'whiskey',
    strength: 3,
    sweetness: 2,
    abv: 24,
    color: '深琥珀',
    difficulty: 2,
    rating: 4.6,
    mbtiMatch: ['ISTP', 'INTP', 'INTJ'],
    description: '烟熏艾莱浮层如雪茄烟圈压在蜂蜜姜香之上，现代酸酒的巅峰之作。',
    story: '2005 年由纽约 Milk & Honey 的 Sam Ross 首创，是 21 世纪传播最广的新经典之一。烟熏威士忌"漂浮"技法让香气分层释放，被业内誉为"一杯会呼吸的酸酒"。',
    method: 'shake',
    methodLabel: '摇和法',
    ingredients: [
      { name: '苏格兰调和威士忌', amount: '50', unit: 'ml', category: 'base' },
      { name: '艾莱单一麦芽威士忌', amount: '10', unit: 'ml', category: 'modifier' },
      { name: '新鲜柠檬汁', amount: '22', unit: 'ml', category: 'acid' },
      { name: '蜂蜜姜糖浆', amount: '15', unit: 'ml', category: 'sweetener' }
    ],
    garnish: '糖渍姜片',
    flavorNotes: ['烟熏', '香料', '柑橘', '复杂'],
    scene: ['独饮', '冬日', '商务'],
    tags: ['现代', '烟熏', 'IBA', '新经典']
  },
  {
    id: 'paper-plane',
    name: '纸飞机',
    nameEn: 'Paper Plane',
    category: 'modern',
    image: '',
    glass: '马天尼杯',
    structure: 'sour',
    baseSpirit: 'whiskey',
    strength: 3,
    sweetness: 2,
    abv: 20,
    color: '金色',
    difficulty: 2,
    rating: 4.5,
    mbtiMatch: ['ENTP', 'ISFP', 'ENFP'],
    description: '四等分的现代经典，苦甜酸三线并行如纸飞机的空中盘旋。',
    story: '2008 年 Sam Ross 与 Sasha Petraske 为纽约 Mint 酒吧开业酒单共创，向 M.I.A. 的歌曲《Paper Planes》致敬。Amaro Nonino 的含蓄草本与阿佩罗的明亮微苦，构成"折纸般精确的平衡"。',
    method: 'shake',
    methodLabel: '摇和法',
    ingredients: [
      { name: '波本威士忌', amount: '30', unit: 'ml', category: 'base' },
      { name: '阿佩罗', amount: '30', unit: 'ml', category: 'modifier' },
      { name: '诺尼诺阿马罗', amount: '30', unit: 'ml', category: 'modifier' },
      { name: '新鲜柠檬汁', amount: '30', unit: 'ml', category: 'acid' }
    ],
    garnish: '无装饰',
    flavorNotes: ['苦味', '柑橘', '草本', '甜美'],
    scene: ['社交', '餐前'],
    tags: ['现代', '新经典', 'IBA', '等分配方']
  },
  {
    id: 'godfather',
    name: '教父',
    nameEn: 'Godfather',
    category: 'spirit-forward',
    image: '',
    glass: '古典杯',
    structure: 'old-fashioned',
    baseSpirit: 'whiskey',
    strength: 4,
    sweetness: 3,
    abv: 30,
    color: '深琥珀',
    difficulty: 1,
    rating: 4.1,
    mbtiMatch: ['ESTJ', 'ISTP', 'INTJ'],
    description: '苏格兰麦芽与杏仁甜香的极简二重奏，如同教父的低语——温和而不可拒绝。',
    story: '1970 年代流行于美国，传说因马龙·白兰度的钟爱而得名。仅两种原料的"两音符和弦"，是那个年代酒吧里最省事也最迷人的选择。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '苏格兰威士忌', amount: '45', unit: 'ml', category: 'base' },
      { name: '杏仁利口酒', amount: '25', unit: 'ml', category: 'modifier' }
    ],
    garnish: '橙皮',
    flavorNotes: ['坚果', '甜美', '干型', '复杂'],
    scene: ['独饮', '餐后'],
    tags: ['经典', '极简', '烈酒']
  },
  // ==================== 朗姆酒 Rum ====================
  {
    id: 'mojito',
    name: '莫吉托',
    nameEn: 'Mojito',
    category: 'tropical',
    image: '',
    glass: '高球杯',
    structure: 'highball',
    baseSpirit: 'rum',
    strength: 2,
    sweetness: 3,
    abv: 13,
    color: '透明微绿',
    difficulty: 2,
    rating: 4.6,
    mbtiMatch: ['ESFP', 'ENFP', 'ESTP'],
    description: '清新活力的热带经典，自由奔放，如同探索者的灵魂。',
    story: '起源于古巴哈瓦那，海明威在 La Bodeguita del Medio 酒吧的墙上留下了"我的莫吉托在 La Bodeguita"的名言，让这款酒名扬天下。',
    method: 'muddle',
    methodLabel: '捣压法',
    ingredients: [
      { name: '白朗姆酒', amount: '45', unit: 'ml', category: 'base' },
      { name: '新鲜青柠汁', amount: '20', unit: 'ml', category: 'acid' },
      { name: '薄荷叶', amount: '10', unit: '片', category: 'modifier' },
      { name: '白砂糖', amount: '10', unit: 'g', category: 'sweetener' },
      { name: '苏打水', amount: '适量', unit: '', category: 'mixer' }
    ],
    garnish: '薄荷枝、青柠角',
    flavorNotes: ['薄荷', '青柠', '气泡', '清爽'],
    scene: ['派对', '夏日', '户外'],
    tags: ['热带', '清爽', '古巴', '夏日', 'IBA']
  },
  {
    id: 'daiquiri',
    name: '戴克利',
    nameEn: 'Daiquiri',
    category: 'classic',
    image: '',
    glass: '马天尼杯',
    structure: 'sour',
    baseSpirit: 'rum',
    strength: 3,
    sweetness: 3,
    abv: 22,
    color: '透明微白',
    difficulty: 1,
    rating: 4.4,
    mbtiMatch: ['ISTP', 'ESTP', 'ENTP'],
    description: '简单纯粹的三合一经典，果敢直接，如同实干家的行事风格。',
    story: '1898 年诞生于古巴的戴克利矿区，由美国采矿工程师 Jennings Cox 发明。海明威也是其忠实爱好者，甚至有自己的特调版本——双份朗姆不加糖。',
    method: 'shake',
    methodLabel: '摇和法',
    ingredients: [
      { name: '白朗姆酒', amount: '60', unit: 'ml', category: 'base' },
      { name: '新鲜青柠汁', amount: '22', unit: 'ml', category: 'acid' },
      { name: '单糖浆', amount: '15', unit: 'ml', category: 'sweetener' }
    ],
    garnish: '青柠轮',
    flavorNotes: ['青柠', '清爽', '微甜', '极简'],
    scene: ['独饮', '派对', '夏日'],
    tags: ['经典', '朗姆', '古巴', '极简']
  },
  {
    id: 'mai-tai',
    name: '迈泰',
    nameEn: 'Mai Tai',
    category: 'tropical',
    image: '',
    glass: '飓风杯',
    structure: 'tiki',
    baseSpirit: 'rum',
    strength: 4,
    sweetness: 3,
    abv: 22,
    color: '琥珀金',
    difficulty: 3,
    rating: 4.6,
    mbtiMatch: ['ESFP', 'ENFP', 'ENTP'],
    description: 'Tiki 文化的巅峰之作，复杂层次中藏着热带岛屿的灵魂。',
    story: '1944 年由 Tiki 文化之父 Donn Beach 的对手 Victor Bergeron（Trader Vic）在加州奥克兰创作。当第一位客人品尝后，她用大溪地语惊呼"Maita\'i roa ae!"（太棒了！），这款酒因此得名。',
    method: 'shake',
    methodLabel: '摇和法',
    ingredients: [
      { name: '陈年朗姆酒', amount: '30', unit: 'ml', category: 'base' },
      { name: '牙买加朗姆酒', amount: '30', unit: 'ml', category: 'base' },
      { name: '橙味利口酒', amount: '15', unit: 'ml', category: 'modifier' },
      { name: '新鲜青柠汁', amount: '22', unit: 'ml', category: 'acid' },
      { name: '杏仁糖浆', amount: '10', unit: 'ml', category: 'sweetener' },
      { name: '单糖浆', amount: '5', unit: 'ml', category: 'sweetener' }
    ],
    garnish: '薄荷枝、青柠壳、热带水果',
    flavorNotes: ['杏仁', '柑橘', '热带水果', '复杂'],
    scene: ['派对', '夏日', '度假'],
    tags: ['Tiki', '热带', '复杂', '标志性', 'IBA']
  },
  {
    id: 'pina-colada',
    name: '椰林飘香',
    nameEn: 'Piña Colada',
    category: 'tropical',
    image: '',
    glass: '飓风杯',
    structure: 'tiki',
    baseSpirit: 'rum',
    strength: 2,
    sweetness: 4,
    abv: 13,
    color: '乳白',
    difficulty: 2,
    rating: 4.3,
    mbtiMatch: ['ESFJ', 'ENFJ', 'ESFP'],
    description: '椰香与菠萝的热带狂欢，每一口都是加勒比海的阳光。',
    story: '1954 年由波多黎各圣胡安的调酒师 Ramón Monchito 用三个月时间研发。1978 年被定为波多黎各国酒。它的成功让椰子奶油成为调酒界的标配材料。',
    method: 'blend',
    methodLabel: '搅拌机法',
    ingredients: [
      { name: '白朗姆酒', amount: '45', unit: 'ml', category: 'base' },
      { name: '椰奶', amount: '45', unit: 'ml', category: 'modifier' },
      { name: '菠萝汁', amount: '90', unit: 'ml', category: 'mixer' },
      { name: '单糖浆', amount: '10', unit: 'ml', category: 'sweetener' }
    ],
    garnish: '菠萝角、樱桃',
    flavorNotes: ['椰子', '菠萝', '奶香', '热带'],
    scene: ['派对', '度假', '夏日'],
    tags: ['热带', '奶香', '波多黎各', '甜品酒', 'IBA']
  },
  {
    id: 'dark-n-stormy',
    name: '黑风暴',
    nameEn: 'Dark \'n Stormy',
    category: 'classic',
    image: '',
    glass: '高球杯',
    structure: 'highball',
    baseSpirit: 'rum',
    strength: 3,
    sweetness: 3,
    abv: 14,
    color: '深琥珀（渐变）',
    difficulty: 1,
    rating: 4.2,
    mbtiMatch: ['ISTP', 'ESTP', 'ENTJ'],
    description: '百慕大的黑色风暴，姜的辛辣与黑朗姆的深邃碰撞。',
    story: '诞生于百慕大，是 Gosling 黑朗姆酒与本土姜汁啤酒的天作之合。Gosling 兄弟甚至为这个名字注册了商标——只有使用 Gosling 黑朗姆调制的才能叫 Dark \'n Stormy。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '黑朗姆酒', amount: '45', unit: 'ml', category: 'base' },
      { name: '姜汁啤酒', amount: '120', unit: 'ml', category: 'mixer' },
      { name: '青柠汁', amount: '10', unit: 'ml', category: 'acid' }
    ],
    garnish: '青柠角',
    flavorNotes: ['姜', '辛辣', '焦糖', '气泡'],
    scene: ['夏日', '户外', '派对'],
    tags: ['经典', '辛辣', '百慕大', '长饮']
  },
  {
    id: 'zombie',
    name: '僵尸',
    nameEn: 'Zombie',
    category: 'tropical',
    image: '',
    glass: '飓风杯',
    structure: 'tiki',
    baseSpirit: 'rum',
    strength: 5,
    sweetness: 3,
    abv: 30,
    color: '深琥珀',
    difficulty: 3,
    rating: 4.5,
    mbtiMatch: ['ENTP', 'ENFP', 'ESTP'],
    description: '三种朗姆的狂欢，Tiki 文化中最危险的诱惑。',
    story: '1934 年由 Donn Beach 在好莱坞的 Don the Beachcomber 酒吧创作，为帮助一位宿醉的商人"复活"。因为喝完一杯就像行尸走肉，故得名"僵尸"。Donn Beach 对配方严格保密，直到去世前才公开。',
    method: 'shake',
    methodLabel: '摇和法',
    ingredients: [
      { name: '牙买加朗姆酒', amount: '30', unit: 'ml', category: 'base' },
      { name: '波多黎各金朗姆', amount: '30', unit: 'ml', category: 'base' },
      { name: '高度朗姆酒', amount: '30', unit: 'ml', category: 'base' },
      { name: '新鲜青柠汁', amount: '22', unit: 'ml', category: 'acid' },
      { name: '法勒南糖浆', amount: '15', unit: 'ml', category: 'sweetener' },
      { name: '西柚汁', amount: '15', unit: 'ml', category: 'mixer' },
      { name: '肉桂糖浆', amount: '10', unit: 'ml', category: 'sweetener' },
      { name: '安格斯特拉苦精', amount: '2', unit: '滴', category: 'modifier' }
    ],
    garnish: '薄荷枝、热带水果',
    flavorNotes: ['肉桂', '热带水果', '辛辣', '复杂'],
    scene: ['派对', '度假', '挑战'],
    tags: ['Tiki', '烈酒', '复杂', '传奇']
  },

  {
    id: 'cuba-libre',
    name: '自由古巴',
    nameEn: 'Cuba Libre',
    category: 'classic',
    image: '',
    glass: '高球杯',
    structure: 'highball',
    baseSpirit: 'rum',
    strength: 2,
    sweetness: 4,
    abv: 10,
    color: '深琥珀',
    difficulty: 1,
    rating: 3.9,
    mbtiMatch: ['ESFP', 'ESTP', 'ESFJ'],
    description: '朗姆、可乐与青柠的大众经典，一杯盛着百年前的自由呐喊。',
    story: '1900 年美西战争后诞生于哈瓦那，"¡Por Cuba libre!"（为了自由的古巴！）是点酒时的祝词。可乐的工业化甜味与青柠的酸让朗姆酒从此走向了全世界。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '白朗姆酒', amount: '50', unit: 'ml', category: 'base' },
      { name: '可乐', amount: '120', unit: 'ml', category: 'mixer' },
      { name: '新鲜青柠汁', amount: '10', unit: 'ml', category: 'acid' }
    ],
    garnish: '青柠角',
    flavorNotes: ['甜美', '焦糖', '青柠', '气泡'],
    scene: ['派对', '夏日', '社交'],
    tags: ['经典', 'IBA', '长饮', '大众']
  },
  {
    id: 'hurricane',
    name: '飓风',
    nameEn: 'Hurricane',
    category: 'tropical',
    image: '',
    glass: '飓风杯',
    structure: 'tiki',
    baseSpirit: 'rum',
    strength: 4,
    sweetness: 4,
    abv: 16,
    color: '粉红',
    difficulty: 2,
    rating: 4.0,
    mbtiMatch: ['ESFP', 'ENFP', 'ESFJ'],
    description: '双朗姆与百香果的飓风级派对酒，以标志性的花形酒杯闻名于世。',
    story: '1940 年代新奥尔良 Pat O\'Brien\'s 酒吧为消化积压的低档朗姆酒而创，配以独特的飓风灯形杯。它是 Mardi Gras 狂欢节的标配，一杯下去"眼前真的会出现风暴"。',
    method: 'shake',
    methodLabel: '摇和法',
    ingredients: [
      { name: '白朗姆酒', amount: '45', unit: 'ml', category: 'base' },
      { name: '黑朗姆酒', amount: '45', unit: 'ml', category: 'base' },
      { name: '百香果汁', amount: '30', unit: 'ml', category: 'acid' },
      { name: '橙汁', amount: '30', unit: 'ml', category: 'acid' },
      { name: '新鲜青柠汁', amount: '15', unit: 'ml', category: 'acid' },
      { name: '红石榴糖浆', amount: '15', unit: 'ml', category: 'sweetener' }
    ],
    garnish: '橙片',
    flavorNotes: ['热带水果', '果味', '甜美', '清爽'],
    scene: ['派对', '夏日', '社交'],
    tags: ['热带', '派对', 'IBA', '大杯']
  },
  {
    id: 'jungle-bird',
    name: '丛林鸟',
    nameEn: 'Jungle Bird',
    category: 'tropical',
    image: '',
    glass: '古典杯',
    structure: 'tiki',
    baseSpirit: 'rum',
    strength: 3,
    sweetness: 3,
    abv: 18,
    color: '深琥珀',
    difficulty: 2,
    rating: 4.2,
    mbtiMatch: ['INFJ', 'ISTP', 'INTJ'],
    description: '金巴利的苦味闯入菠萝的甜浪，热带风情里的深邃反转。',
    story: '1978 年诞生于吉隆坡希尔顿酒店 Aviary Bar 的迎宾酒，杯沿的纸质扇尾鸟装饰是标志。它是少数把金巴利带入提基世界的先驱，苦甜平衡让它从酒店赠饮逆袭为全球鸡尾酒单常客。',
    method: 'shake',
    methodLabel: '摇和法',
    ingredients: [
      { name: '黑朗姆酒', amount: '45', unit: 'ml', category: 'base' },
      { name: '金巴利', amount: '22', unit: 'ml', category: 'modifier' },
      { name: '菠萝汁', amount: '45', unit: 'ml', category: 'acid' },
      { name: '新鲜青柠汁', amount: '15', unit: 'ml', category: 'acid' },
      { name: '单糖浆', amount: '15', unit: 'ml', category: 'sweetener' }
    ],
    garnish: '菠萝角',
    flavorNotes: ['热带水果', '菠萝', '苦味', '甜美'],
    scene: ['夏日', '派对', '独饮'],
    tags: ['热带', '提基', 'IBA', '苦甜']
  },
  {
    id: 'el-presidente',
    name: '总统',
    nameEn: 'El Presidente',
    category: 'modern',
    image: '',
    glass: '马天尼杯',
    structure: 'martini',
    baseSpirit: 'rum',
    strength: 3,
    sweetness: 3,
    abv: 26,
    color: '金色',
    difficulty: 2,
    rating: 4.2,
    mbtiMatch: ['ENTJ', 'ENFJ', 'ESFJ'],
    description: '古巴黄金年代的总统级优雅，朗姆酒版的"完美马天尼"。',
    story: '1920 年代哈瓦那禁酒令避风港时期的作品，据说因总统 Gerardo Machado 钟爱而得名。当时《Savoy 鸡尾酒书》称其为"古巴的完美鸡尾酒"，是朗姆酒精致化路线的巅峰。',
    method: 'stir',
    methodLabel: '搅拌法',
    ingredients: [
      { name: '白朗姆酒', amount: '45', unit: 'ml', category: 'base' },
      { name: '橙味美思', amount: '20', unit: 'ml', category: 'modifier' },
      { name: '君度橙酒', amount: '15', unit: 'ml', category: 'modifier' },
      { name: '红石榴糖浆', amount: '5', unit: 'ml', category: 'sweetener' }
    ],
    garnish: '橙皮',
    flavorNotes: ['橙子', '甜美', '果味', '干型'],
    scene: ['商务', '餐前', '社交'],
    tags: ['经典', 'IBA', '哈瓦那']
  },
  // ==================== 龙舌兰 Tequila ====================
  {
    id: 'margarita',
    name: '玛格丽特',
    nameEn: 'Margarita',
    category: 'classic',
    image: '',
    glass: '玛格丽特杯',
    structure: 'margarita',
    baseSpirit: 'tequila',
    strength: 3,
    sweetness: 2,
    abv: 20,
    color: '透明微白',
    difficulty: 2,
    rating: 4.6,
    mbtiMatch: ['ESFJ', 'ENFJ', 'ESTP'],
    description: '盐边与酸橙的经典搭配，热情而不失优雅，如同主人公的魅力。',
    story: '关于玛格丽特的起源有多种传说，最浪漫的说法是一位墨西哥调酒师为纪念逝去的爱人 Margarita 而创作。盐边象征泪水，酸涩中带着甜美。',
    method: 'shake',
    methodLabel: '摇和法',
    ingredients: [
      { name: '龙舌兰酒', amount: '45', unit: 'ml', category: 'base' },
      { name: '君度橙酒', amount: '20', unit: 'ml', category: 'modifier' },
      { name: '新鲜青柠汁', amount: '20', unit: 'ml', category: 'acid' }
    ],
    garnish: '青柠轮、盐边',
    flavorNotes: ['龙舌兰', '青柠', '柑橘', '盐'],
    scene: ['派对', '社交', '夏日'],
    tags: ['经典', '墨西哥', '酸甜', '盐边', 'IBA']
  },
  {
    id: 'tequila-sunrise',
    name: '龙舌兰日出',
    nameEn: 'Tequila Sunrise',
    category: 'tropical',
    image: '',
    glass: '高球杯',
    structure: 'highball',
    baseSpirit: 'tequila',
    strength: 2,
    sweetness: 3,
    abv: 12,
    color: '橙红渐变',
    difficulty: 1,
    rating: 4.1,
    mbtiMatch: ['ESFP', 'ENFP', 'ISFP'],
    description: '杯中日出，视觉与味觉的双重享受。',
    story: '1970 年代因滚石乐队在巡演中大量饮用而走红。Eagles 乐队的歌曲《Tequila Sunrise》更将其推向了文化符号的高度。它最大的魅力在于——红石榴糖浆缓缓下沉形成的渐变效果。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '龙舌兰酒', amount: '45', unit: 'ml', category: 'base' },
      { name: '新鲜橙汁', amount: '90', unit: 'ml', category: 'mixer' },
      { name: '红石榴糖浆', amount: '15', unit: 'ml', category: 'sweetener' }
    ],
    garnish: '橙片、樱桃',
    flavorNotes: ['橙子', '石榴', '果味', '微甜'],
    scene: ['派对', '夏日', '早午餐'],
    tags: ['热带', '视觉系', '摇滚', '渐变色']
  },
  {
    id: 'paloma',
    name: '帕洛玛',
    nameEn: 'Paloma',
    category: 'tropical',
    image: '',
    glass: '高球杯',
    structure: 'highball',
    baseSpirit: 'tequila',
    strength: 2,
    sweetness: 2,
    abv: 12,
    color: '淡粉',
    difficulty: 1,
    rating: 4.3,
    mbtiMatch: ['ESTP', 'ESFP', 'ISTP'],
    description: '墨西哥最受欢迎的长饮，西柚的清爽与龙舌兰完美共鸣。',
    story: '虽然在海外不如玛格丽特出名，但在墨西哥本土，Paloma 才是真正的国民鸡尾酒。名字意为"鸽子"，象征和平与清新。它简单到只需三种材料，却有着令人上瘾的清爽。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '龙舌兰酒', amount: '45', unit: 'ml', category: 'base' },
      { name: '西柚苏打水', amount: '120', unit: 'ml', category: 'mixer' },
      { name: '新鲜青柠汁', amount: '15', unit: 'ml', category: 'acid' }
    ],
    garnish: '西柚片、盐边（可选）',
    flavorNotes: ['西柚', '气泡', '清爽', '微咸'],
    scene: ['夏日', '户外', '派对'],
    tags: ['墨西哥', '清爽', '国民', '长饮']
  },
  {
    id: 'el-diablo',
    name: '魔鬼',
    nameEn: 'El Diablo',
    category: 'modern',
    image: '',
    glass: '高球杯',
    structure: 'highball',
    baseSpirit: 'tequila',
    strength: 3,
    sweetness: 3,
    abv: 15,
    color: '深紫红',
    difficulty: 2,
    rating: 4.2,
    mbtiMatch: ['ENTP', 'ENFP', 'INFJ'],
    description: '黑加仑与姜的暗黑诱惑，名字邪恶但味道迷人。',
    story: '1946 年由 Trader Vic 创作，最初名为"Mexican El Diablo"。黑加仑利口酒赋予它深邃的紫红色，姜汁啤酒则带来辛辣的回响。它证明了龙舌兰不只是适合玛格丽特。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '龙舌兰酒', amount: '45', unit: 'ml', category: 'base' },
      { name: '黑加仑利口酒', amount: '15', unit: 'ml', category: 'modifier' },
      { name: '新鲜青柠汁', amount: '15', unit: 'ml', category: 'acid' },
      { name: '姜汁啤酒', amount: '90', unit: 'ml', category: 'mixer' }
    ],
    garnish: '青柠角',
    flavorNotes: ['黑加仑', '姜', '辛辣', '果味'],
    scene: ['派对', '社交', '秋冬'],
    tags: ['现代', '暗黑', '果味', '个性']
  },
  {
    id: 'mezcal-negroni',
    name: '梅斯卡尔尼格罗尼',
    nameEn: 'Mezcal Negroni',
    category: 'modern',
    image: '',
    glass: '古典杯',
    structure: 'old-fashioned',
    baseSpirit: 'tequila',
    strength: 4,
    sweetness: 2,
    abv: 25,
    color: '深琥珀',
    difficulty: 1,
    rating: 4.5,
    mbtiMatch: ['INTP', 'INTJ', 'ISTP'],
    description: '烟熏龙舌兰的叛逆演绎，尼格罗尼家族中最有个性的成员。',
    story: 'Mezcal Negroni 是经典鸡尾酒现代化改编的代表作。将金酒替换为烟熏风味的梅斯卡尔，让原本清爽的尼格罗尼多了荒野篝火般的烟熏层次，深受精酿鸡尾酒吧的喜爱。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '梅斯卡尔酒', amount: '30', unit: 'ml', category: 'base' },
      { name: '甜味美思', amount: '30', unit: 'ml', category: 'modifier' },
      { name: '金巴利', amount: '30', unit: 'ml', category: 'modifier' }
    ],
    garnish: '橙皮',
    flavorNotes: ['烟熏', '苦味', '草本', '龙舌兰'],
    scene: ['独饮', '餐前', '秋冬'],
    tags: ['现代', '烟熏', '改编', '个性']
  },

  {
    id: 'tommys-margarita',
    name: '汤米的玛格丽特',
    nameEn: "Tommy's Margarita",
    category: 'modern',
    image: '',
    glass: '古典杯',
    structure: 'margarita',
    baseSpirit: 'tequila',
    strength: 3,
    sweetness: 2,
    abv: 22,
    color: '淡绿',
    difficulty: 1,
    rating: 4.5,
    mbtiMatch: ['ISFP', 'ISTP', 'ESFP'],
    description: '去掉橙酒的极简玛格丽特，让龙舌兰的植物本味站上主角位。',
    story: '1990 年代旧金山 Tommy\'s 餐厅的 Julio Bermejo 首创，用龙舌兰糖浆替代君度橙酒。这杯"减法鸡尾酒"重新定义了玛格丽特，被票选为 21 世纪最具影响力的鸡尾酒之一。',
    method: 'shake',
    methodLabel: '摇和法',
    ingredients: [
      { name: '龙舌兰酒', amount: '60', unit: 'ml', category: 'base' },
      { name: '新鲜青柠汁', amount: '30', unit: 'ml', category: 'acid' },
      { name: '龙舌兰糖浆', amount: '15', unit: 'ml', category: 'sweetener' }
    ],
    garnish: '青柠轮',
    flavorNotes: ['青柠', '柑橘', '清爽', '果味'],
    scene: ['夏日', '社交', '户外'],
    tags: ['现代', 'IBA', '新经典', '极简']
  },
  {
    id: 'batanga',
    name: '巴坦加',
    nameEn: 'Batanga',
    category: 'modern',
    image: '',
    glass: '高球杯',
    structure: 'highball',
    baseSpirit: 'tequila',
    strength: 2,
    sweetness: 4,
    abv: 12,
    color: '深琥珀',
    difficulty: 1,
    rating: 4.0,
    mbtiMatch: ['ESTP', 'ESFP', 'ENTP'],
    description: '龙舌兰与可乐的墨西哥乡土混搭，盐边是点睛的魔法。',
    story: '1960 年代诞生于 Tequila 镇的 La Capilla 酒吧，老板 Don Javier Delgado Corona 用长刀搅拌而闻名。"Batanga"在当地方言里意指"强壮的男孩"，是墨西哥乡村酒吧的灵魂饮品。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '龙舌兰酒', amount: '50', unit: 'ml', category: 'base' },
      { name: '可乐', amount: '120', unit: 'ml', category: 'mixer' },
      { name: '新鲜青柠汁', amount: '15', unit: 'ml', category: 'acid' }
    ],
    garnish: '盐边',
    flavorNotes: ['焦糖', '青柠', '甜美', '气泡'],
    scene: ['派对', '夏日', '社交'],
    tags: ['现代', '墨西哥', '长饮']
  },
  // ==================== 伏特加 Vodka ====================
  {
    id: 'espresso-martini',
    name: '浓缩咖啡马天尼',
    nameEn: 'Espresso Martini',
    category: 'modern',
    image: '',
    glass: '马天尼杯',
    structure: 'martini',
    baseSpirit: 'vodka',
    strength: 3,
    sweetness: 3,
    abv: 22,
    color: '深棕',
    difficulty: 2,
    rating: 4.7,
    mbtiMatch: ['ENTP', 'INTP', 'ENTJ'],
    description: '咖啡与酒精的完美碰撞，创意十足，如同发明家的灵感迸发。',
    story: '1983 年由伦敦调酒师 Dick Bradsell 为一位超模创作。她说"唤醒我，然后灌醉我"，于是这款兼具提神与微醺的酒诞生了。',
    method: 'shake',
    methodLabel: '摇和法',
    ingredients: [
      { name: '伏特加', amount: '45', unit: 'ml', category: 'base' },
      { name: '浓缩咖啡', amount: '30', unit: 'ml', category: 'modifier' },
      { name: '咖啡利口酒', amount: '15', unit: 'ml', category: 'modifier' },
      { name: '单糖浆', amount: '10', unit: 'ml', category: 'sweetener' }
    ],
    garnish: '三颗咖啡豆',
    flavorNotes: ['咖啡', '焦糖', '微甜', '丝滑'],
    scene: ['派对', '餐后', '提神'],
    tags: ['现代', '咖啡', '提神', '派对']
  },
  {
    id: 'moscow-mule',
    name: '莫斯科骡子',
    nameEn: 'Moscow Mule',
    category: 'classic',
    image: '',
    glass: '铜杯',
    structure: 'highball',
    baseSpirit: 'vodka',
    strength: 2,
    sweetness: 3,
    abv: 13,
    color: '透明',
    difficulty: 1,
    rating: 4.4,
    mbtiMatch: ['ESTP', 'ESFP', 'ENTJ'],
    description: '铜杯中的辛辣气泡，姜的活力与伏特加的纯净相得益彰。',
    story: '1941 年诞生于洛杉矶的 Cock \'n Bull 酒吧，是三方的天才合作——Smirnoff 伏特加需要打开美国市场，Cock \'n Bull 的姜汁啤酒销量不佳，而一位俄罗斯移民带来了铜杯的创意。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '伏特加', amount: '45', unit: 'ml', category: 'base' },
      { name: '姜汁啤酒', amount: '120', unit: 'ml', category: 'mixer' },
      { name: '新鲜青柠汁', amount: '10', unit: 'ml', category: 'acid' }
    ],
    garnish: '青柠角',
    flavorNotes: ['姜', '辛辣', '气泡', '青柠'],
    scene: ['派对', '社交', '夏日'],
    tags: ['经典', '铜杯', '辛辣', '清爽', 'IBA']
  },
  {
    id: 'cosmopolitan',
    name: '大都会',
    nameEn: 'Cosmopolitan',
    category: 'modern',
    image: '',
    glass: '马天尼杯',
    structure: 'sour',
    baseSpirit: 'vodka',
    strength: 3,
    sweetness: 3,
    abv: 20,
    color: '粉红',
    difficulty: 2,
    rating: 4.2,
    mbtiMatch: ['ESFJ', 'ENFJ', 'ESFP'],
    description: '粉红时代的时尚符号，蔓越莓与柑橘的都市优雅。',
    story: '1990 年代因《欲望都市》中 Carrie Bradshaw 的标志性饮品而风靡全球。虽然起源可以追溯到更早的变体，但它的流行完美地定义了一个时代的都市女性气质。',
    method: 'shake',
    methodLabel: '摇和法',
    ingredients: [
      { name: '柑橘伏特加', amount: '45', unit: 'ml', category: 'base' },
      { name: '君度橙酒', amount: '15', unit: 'ml', category: 'modifier' },
      { name: '蔓越莓汁', amount: '30', unit: 'ml', category: 'mixer' },
      { name: '新鲜青柠汁', amount: '10', unit: 'ml', category: 'acid' }
    ],
    garnish: '橙皮、柠檬皮',
    flavorNotes: ['蔓越莓', '柑橘', '微酸', '果味'],
    scene: ['社交', '派对', '约会'],
    tags: ['现代', '粉红', '都市', '时尚']
  },
  {
    id: 'bloody-mary',
    name: '血腥玛丽',
    nameEn: 'Bloody Mary',
    category: 'classic',
    image: '',
    glass: '高球杯',
    structure: 'highball',
    baseSpirit: 'vodka',
    strength: 2,
    sweetness: 1,
    abv: 12,
    color: '深红',
    difficulty: 2,
    rating: 4.0,
    mbtiMatch: ['ISTJ', 'ESTJ', 'ISTP'],
    description: '液体沙拉般的复杂层次，最不像酒的酒，早餐的叛逆选择。',
    story: '1920 年代由巴黎 Harry\'s New York Bar 的调酒师 Fernand Petiot 创作。最初只是伏特加加番茄汁的简单组合，后来逐渐演变成世界上最复杂的鸡尾酒配方之一，甚至有"可以嚼的酒"之称。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '伏特加', amount: '45', unit: 'ml', category: 'base' },
      { name: '番茄汁', amount: '90', unit: 'ml', category: 'mixer' },
      { name: '新鲜柠檬汁', amount: '15', unit: 'ml', category: 'acid' },
      { name: '伍斯特酱', amount: '3', unit: '滴', category: 'modifier' },
      { name: '塔巴斯科辣酱', amount: '2', unit: '滴', category: 'modifier' },
      { name: '黑胡椒', amount: '少许', unit: '', category: 'modifier' },
      { name: '盐', amount: '少许', unit: '', category: 'modifier' }
    ],
    garnish: '芹菜杆、柠檬角',
    flavorNotes: ['番茄', '辛辣', '咸味', '复杂'],
    scene: ['早午餐', '解酒', '秋冬'],
    tags: ['经典', '复杂', '早餐', '解酒', 'IBA']
  },
  {
    id: 'white-russian',
    name: '白俄罗斯',
    nameEn: 'White Russian',
    category: 'creamy',
    image: '',
    glass: '古典杯',
    structure: 'cream',
    baseSpirit: 'vodka',
    strength: 2,
    sweetness: 4,
    abv: 15,
    color: '奶咖',
    difficulty: 1,
    rating: 4.2,
    mbtiMatch: ['ISFJ', 'INFP', 'ISFP'],
    description: '咖啡利口酒与奶油的丝滑交融，甜品般温柔的精神慰藉。',
    story: '1965 年首次出现在配方书中，但真正让它成为文化符号的是 1998 年的电影《谋杀绿脚趾》。片中 Jeff Bridges 饰演的 Dude 无论何时何地都在喝 White Russian，让这款酒成为"佛系生活"的代言。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '伏特加', amount: '45', unit: 'ml', category: 'base' },
      { name: '咖啡利口酒', amount: '22', unit: 'ml', category: 'modifier' },
      { name: '淡奶油', amount: '30', unit: 'ml', category: 'modifier' }
    ],
    garnish: '无',
    flavorNotes: ['咖啡', '奶油', '丝滑', '甜品'],
    scene: ['独饮', '餐后', '冬日'],
    tags: ['奶油', '甜品', '电影', '丝滑']
  },

  {
    id: 'black-russian',
    name: '黑俄罗斯',
    nameEn: 'Black Russian',
    category: 'spirit-forward',
    image: '',
    glass: '古典杯',
    structure: 'old-fashioned',
    baseSpirit: 'vodka',
    strength: 4,
    sweetness: 3,
    abv: 26,
    color: '深琥珀',
    difficulty: 1,
    rating: 4.0,
    mbtiMatch: ['INTJ', 'ISTP', 'ENTJ'],
    description: '只有两种原料的深邃短饮，如午夜咖啡般冷峻直接。',
    story: '1949 年布鲁塞尔大都会酒店，调酒师 Gustave Tops 为美国驻卢森堡大使 Pearl Mesta 创制。冷战初期的命名自带时代张力——"黑色"是咖啡利口酒，"俄罗斯"是伏特加。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '伏特加', amount: '45', unit: 'ml', category: 'base' },
      { name: '咖啡利口酒', amount: '25', unit: 'ml', category: 'modifier' }
    ],
    garnish: '柠檬皮',
    flavorNotes: ['咖啡', '焦糖', '甜美', '干型'],
    scene: ['独饮', '餐后'],
    tags: ['经典', 'IBA', '极简', '餐后酒']
  },
  {
    id: 'screwdriver',
    name: '螺丝刀',
    nameEn: 'Screwdriver',
    category: 'classic',
    image: '',
    glass: '高球杯',
    structure: 'highball',
    baseSpirit: 'vodka',
    strength: 2,
    sweetness: 3,
    abv: 11,
    color: '金色',
    difficulty: 1,
    rating: 3.8,
    mbtiMatch: ['ESFJ', 'ESFP', 'ENFJ'],
    description: '伏特加与橙汁的黄金比例，简单到不可能失败的大众经典。',
    story: '二战后伊朗油田的美国工人们用螺丝刀搅拌伏特加橙汁而得名——工人智慧版的鸡尾酒。1970 年代随着"Harvey Wallbanger"变体风靡，但原版始终是简单主义的代名词。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '伏特加', amount: '45', unit: 'ml', category: 'base' },
      { name: '橙汁', amount: '90', unit: 'ml', category: 'acid' }
    ],
    garnish: '橙片',
    flavorNotes: ['橙子', '甜美', '果味'],
    scene: ['夏日', '社交', '派对'],
    tags: ['经典', 'IBA', '简单', '早午餐']
  },
  {
    id: 'sex-on-the-beach',
    name: '性感沙滩',
    nameEn: 'Sex on the Beach',
    category: 'tropical',
    image: '',
    glass: '高球杯',
    structure: 'highball',
    baseSpirit: 'vodka',
    strength: 2,
    sweetness: 4,
    abv: 11,
    color: '粉红',
    difficulty: 1,
    rating: 3.9,
    mbtiMatch: ['ESFP', 'ENFP', 'ESFJ'],
    description: '蜜桃与蔓越莓的度假风味，名字比配方更早红遍全球。',
    story: '1980 年代诞生于美国佛罗里达，一说由调酒师 Ted Pizio 为推广蜜桃利口酒所创，名字源自"春假沙滩"的联想，随着旅游潮传遍了地中海沿岸的每一座度假酒店。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '伏特加', amount: '40', unit: 'ml', category: 'base' },
      { name: '蜜桃利口酒', amount: '20', unit: 'ml', category: 'modifier' },
      { name: '蔓越莓汁', amount: '40', unit: 'ml', category: 'acid' },
      { name: '橙汁', amount: '40', unit: 'ml', category: 'acid' }
    ],
    garnish: '橙片',
    flavorNotes: ['果味', '莓果', '甜美', '清爽'],
    scene: ['派对', '夏日', '社交'],
    tags: ['现代', '派对', 'IBA', '度假']
  },
  // 多基酒款，按传统主基调归伏特加
  {
    id: 'long-island-iced-tea',
    name: '长岛冰茶',
    nameEn: 'Long Island Iced Tea',
    category: 'modern',
    image: '',
    glass: '柯林斯杯',
    structure: 'collins',
    baseSpirit: 'vodka',
    strength: 5,
    sweetness: 3,
    abv: 22,
    color: '深琥珀',
    difficulty: 2,
    rating: 4.1,
    mbtiMatch: ['ESTP', 'ENTP', 'ESFP'],
    description: '五种基酒的强力联盟，柠檬与可乐伪装成温和的"冰茶"。',
    story: '1970 年代纽约长岛橡树海滩酒庄酒吧的 Bob Butt 在调酒竞赛中首创。看似冰茶实则烈性十足，是全球夜店的"后劲之王"，也常年位列"最易翻车"鸡尾酒榜首。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '伏特加', amount: '15', unit: 'ml', category: 'base' },
      { name: '金酒', amount: '15', unit: 'ml', category: 'base' },
      { name: '白朗姆酒', amount: '15', unit: 'ml', category: 'base' },
      { name: '龙舌兰酒', amount: '15', unit: 'ml', category: 'base' },
      { name: '君度橙酒', amount: '15', unit: 'ml', category: 'modifier' },
      { name: '新鲜柠檬汁', amount: '25', unit: 'ml', category: 'acid' },
      { name: '单糖浆', amount: '15', unit: 'ml', category: 'sweetener' },
      { name: '可乐', amount: '30', unit: 'ml', category: 'mixer' }
    ],
    garnish: '柠檬片',
    flavorNotes: ['柑橘', '甜美', '复杂', '焦糖'],
    scene: ['派对', '社交'],
    tags: ['现代', 'IBA', '烈性', '派对']
  },
  // ==================== 补充经典 ====================
  {
    id: 'aperol-spritz',
    name: '阿佩罗橙光',
    nameEn: 'Aperol Spritz',
    category: 'classic',
    image: '',
    glass: '葡萄酒杯',
    structure: 'highball',
    baseSpirit: 'gin',
    strength: 1,
    sweetness: 3,
    abv: 8,
    color: '亮橙',
    difficulty: 1,
    rating: 4.3,
    mbtiMatch: ['ENFJ', 'ESFJ', 'ENFP'],
    description: '意大利的橙色夕阳，低酒精度的社交良伴。',
    story: '源自 19 世纪奥匈帝国的威尼斯地区，最初是德国士兵用苏打水稀释意大利葡萄酒的喝法。Aperol 品牌在 1950 年代将其标准化，如今已成为意大利 Aperitivo 文化的全球代言。',
    method: 'build',
    methodLabel: '直调法',
    ingredients: [
      { name: '阿佩罗', amount: '60', unit: 'ml', category: 'modifier' },
      { name: '普罗塞克起泡酒', amount: '90', unit: 'ml', category: 'base' },
      { name: '苏打水', amount: '30', unit: 'ml', category: 'mixer' }
    ],
    garnish: '橙片',
    flavorNotes: ['橙子', '气泡', '微苦', '草本'],
    scene: ['社交', '餐前', '夏日'],
    tags: ['经典', '低酒精', '意大利', '社交', 'IBA']
  }
];
